Что, если мы добавим в наш класс *Divider* массив, который будем динамически создавать в конструкторе:

Вывод данной программы:
<code>
allocating cache                                                              
cache allocated                                                                  
Exception caught: Divider can not be 0!</code>

Поскольку объект не был до конца создан, то и деструктор не будет вызван. Однако мы уже 
успели создать динамический выделенный массив — *_cache*. Важно помнить, что исключение 
передаёт управление обработчику исключений, и весь код за ним не будет исполнен, тогда 
нам следует создавать массив после генерации исключений, то есть когда мы уже уверены, 
что все операции правильны.

<code>Другими словами, мы с вами в ответе за подчистку ресурсов созданных в конструкторе, если генерируем исключение!</code>
