# Throw внутри catch блока
Могут случиться ситуации, когда мы хотим перехватить исключение, но не хотим (или не можем) полностью обработать его в точке, где мы его поймали. Другими словам, когда исключение попало в в наш блок catch, мы не хотим полностью обрабатывать это исключение или не имеем всю информацию, чтобы его обработать. Так часто происходит, если мы хотим зарегистрировать ошибку (то есть сохранить сообщение в журнальный файл или записать в стандартный вывод), однако при этом у текущего обработчика нет возможности отреагировать на ошибку, и тогда мы можем передать ошибку дальше по стеку, чтобы другой (внешний) обработчик исключений перехватил данное исключение, то есть тот, который может действительно отреагировать на ошибку и обработать ее.

